/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { XApiMessage } from "./components/demo-eom/demo-eom";
export namespace Components {
    interface DemoEom {
    }
    interface TaskOne {
    }
    interface TaskThree {
    }
    interface TaskTwo {
    }
}
declare global {
    interface HTMLDemoEomElement extends Components.DemoEom, HTMLStencilElement {
    }
    var HTMLDemoEomElement: {
        prototype: HTMLDemoEomElement;
        new (): HTMLDemoEomElement;
    };
    interface HTMLTaskOneElement extends Components.TaskOne, HTMLStencilElement {
    }
    var HTMLTaskOneElement: {
        prototype: HTMLTaskOneElement;
        new (): HTMLTaskOneElement;
    };
    interface HTMLTaskThreeElement extends Components.TaskThree, HTMLStencilElement {
    }
    var HTMLTaskThreeElement: {
        prototype: HTMLTaskThreeElement;
        new (): HTMLTaskThreeElement;
    };
    interface HTMLTaskTwoElement extends Components.TaskTwo, HTMLStencilElement {
    }
    var HTMLTaskTwoElement: {
        prototype: HTMLTaskTwoElement;
        new (): HTMLTaskTwoElement;
    };
    interface HTMLElementTagNameMap {
        "demo-eom": HTMLDemoEomElement;
        "task-one": HTMLTaskOneElement;
        "task-three": HTMLTaskThreeElement;
        "task-two": HTMLTaskTwoElement;
    }
}
declare namespace LocalJSX {
    interface DemoEom {
        "onXApiMessage"?: (event: CustomEvent<XApiMessage>) => void;
    }
    interface TaskOne {
    }
    interface TaskThree {
    }
    interface TaskTwo {
    }
    interface IntrinsicElements {
        "demo-eom": DemoEom;
        "task-one": TaskOne;
        "task-three": TaskThree;
        "task-two": TaskTwo;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "demo-eom": LocalJSX.DemoEom & JSXBase.HTMLAttributes<HTMLDemoEomElement>;
            "task-one": LocalJSX.TaskOne & JSXBase.HTMLAttributes<HTMLTaskOneElement>;
            "task-three": LocalJSX.TaskThree & JSXBase.HTMLAttributes<HTMLTaskThreeElement>;
            "task-two": LocalJSX.TaskTwo & JSXBase.HTMLAttributes<HTMLTaskTwoElement>;
        }
    }
}
